---
title: "R Notebook"
output: html_notebook
---

```{r data import,include=FALSE}
library(tidyverse)

# Load injection order file
inj_order <- read.csv("data/inject_order.csv", stringsAsFactors = F)

# Load positive mode data file
pos_ori <- read.csv("data/pos-ori.csv", stringsAsFactors = F)

pos_ms2 <- dplyr::select(pos_ori, id, MS2.name)  #select metabolites id and MS2 names
pos_ms2$MS2.name <- as.character(pos_ms2$MS2.name)
pos_inf <- dplyr::select(pos_ori, id, MS2.name, mzmed,rtmed)  #select metabolites id and MS2 names

pos_pro <- dplyr::select(pos_ori, -2, -3, -4, -5, -6, -7, -8)  #select feature profiles for each sample

sampid <- names(pos_pro) %>% str_replace("[0-9][0-9]_pos\\.[ABCD]|[0-9][0-9]_pos\\.QC", "")
names(pos_pro) <- sampid
pos_pro <- dplyr::rename(pos_pro, QC10 = QC0010)
```

```{r data for statTarget, include=FALSE}
# Get files ready for statTarget sample list file
samp_list <- inj_order
samp_list$batch <- rep(c(1), time(78))
samp_list$class[samp_list$class == "q"] <- "NA"
samp_list <- dplyr::arrange(samp_list, order)
write.csv(samp_list, "data/samp_list.csv", row.names = F)
# Feature file
samp_fea <- dplyr::rename(pos_pro, name = id)
write.csv(samp_fea, "data/samp_fea.csv", row.names = F)
```

```{r QC normalization, eval = FALSE}
# QC-RLSC normalization
library(statTarget)
shiftCor("data/samp_list.csv", "data/samp_fea.csv", Frule = 0.9, MLmethod = "QCRLSC", QCspan = 0, imputeM = "KNN")
```

```{r MSTUS, include=FALSE}
file.copy("statTarget/shiftCor/After_shiftCor/shift_all_cor.csv","data/qcrlsc-all-pos.csv")
qcnorm_pos <- read.csv("data/qcrlsc-all-pos.csv", header = F, stringsAsFactors = F)
colnames(qcnorm_pos) <- qcnorm_pos[1, ]
qcnorm_pos <- as.data.frame(qcnorm_pos[-1, ])

# MSTUS to eliminate osmolity effect
qcnorm_pos$rowsum <- rowSums(qcnorm_pos[3:1853], na.rm = FALSE)
for (i in 3:1853) {
    qcnorm_pos[, i] <- qcnorm_pos[, i]/qcnorm_pos[, "rowsum"]
}
qcnorm_pos <- as.data.frame(qcnorm_pos[, -1854])
```

```{r data of AD and ABC,include=FALSE}
#data for A and D, data for A,B and C
library(tidyverse)

norm_pos <- qcnorm_pos[!is.na(qcnorm_pos$class),]#remove qc samples

normAD_pos <-norm_pos[norm_pos$class=="a"|norm_pos$class=="d",]%>% dplyr::arrange(sample) %>% dplyr::slice(-27,-28)

normABC_pos<-norm_pos[norm_pos$class=="a"|norm_pos$class=="b"|norm_pos$class=="c",]%>% dplyr::arrange(sample)%>% dplyr::slice(-43,-44)
```


```{r transformation and scaling,include=FALSE}

library(statTarget)
write.csv(norm_pos,"data/mstus_pos.csv",row.names = F)
statAnalysis("data/mstus_pos.csv",Frule = 0.8, normM = "NONE", imputeM = "KNN", glog = TRUE,scaling = "Pareto")
file.copy("statTarget/statAnalysis/scaleData_Pareto/ProcessedTable.csv","data/ts_all_pos.csv") #copy transformed and scaled data 

```

```{r tidy data of ts_all,include=FALSE}

ts_pos <- read.csv("data/ts_all_pos.csv",stringsAsFactors = F,header = F)
colnames(ts_pos) <- ts_pos[1,]
ts_pos <- as.data.frame(ts_pos[-1,])
ts_col <- names(ts_pos) %>% str_replace("X","")
names(ts_pos) <- ts_col
colnames(ts_pos) <- pos_ms2$MS2.name[match(names(ts_pos),pos_ms2$id)]

col12 <- names(ts_pos)
col12[is.na(col12)] <- "sample"
names(ts_pos) <- col12
ts_pos <- ts_pos %>% dplyr::arrange(sample) %>% dplyr::slice(-43,-44,-61,-62)
ts_pos$class <- rep(c("a","b","c","d"),times=c(16,16,16,16))
ts_pos <- dplyr::select(ts_pos,sample,class,everything())



ts_posMS2 <- ts_pos %>% dplyr::select(-contains("unknown"))

#Write data file to csv: After QCRLSC, MSTUS, log transformation and Pareto scaling

write.csv(ts_pos,"data/ts all with MS2 names_pos.csv",row.names = F)

write.csv(ts_posMS2,"data/ts all with known MS2_pos.csv",row.names = F)

```



```{r data file for comparisons, include=FALSE}

ab_posMS2 <- dplyr::slice(ts_posMS2,1:32)

ab_pos <- dplyr::slice(ts_pos,1:32)

ac_posMS2 <- dplyr::slice(ts_posMS2,1:16,33:48)


ac_pos <- dplyr::slice(ts_pos,1:16,33:48)

ad_posMS2 <- dplyr::slice(ts_posMS2,1:16,49:64)

ad_pos<- dplyr::slice(ts_pos,1:16,49:64)

bc_posMS2 <- dplyr::slice(ts_posMS2,17:48)

bc_pos <- dplyr::slice(ts_pos,17:48)

bd_posMS2 <- dplyr::slice(ts_posMS2,17:32,49:64)

bd_pos <- dplyr::slice(ts_pos,17:32,49:64)

cd_posMS2 <- dplyr::slice(ts_posMS2,33:64)

cd_pos <- dplyr::slice(ts_pos,33:64)

abc_posMS2 <- dplyr::slice(ts_posMS2,1:48)

abc_pos <- dplyr::slice(ts_pos,1:48)
```


```{r data file for time-series analysis using MetaboAnalystR,include=FALSE}
abc_posMS2$time <- rep(c(1:3),times=c(16,16,16))
abc_posMS2$subject <- rep(c(1:16),times=3)
abc_posMS2 <- abc_posMS2 %>% dplyr::select(sample,time,subject,everything()) %>% dplyr::arrange(subject,time) %>% dplyr::select(-class)

write.csv(abc_posMS2,"data/time series ABC_pos.csv",row.names = F)
```

```{r time-series analysis using MetaboAnalystR, include=FALSE}
library(MetaboAnalystR)


mSet<-InitDataObjects("conc", "ts", FALSE)
mSet<-SetDesignType(mSet, "time0")
mSet<-Read.TextData(mSet, "data/time series ABC_pos.csv", "rowts", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "NULL", "NULL", "NULL", ratio=FALSE, ratioNum=20)
timese<-performMB(mSet, 10)
timese_result <- as.data.frame(timese$analSet)
write.csv(timese_result,"data/time series-ABC-results_pos.csv")

```

```{r PLS analysis of AC using MetaboAnalystR,include=FALSE}
library(MetaboAnalystR)

ac_posMS2$Label=c(1:16,-1:-16)
ac_posMS2 <- ac_posMS2 %>% dplyr::select(sample,Label,everything()) %>% dplyr::select(-class)

write.csv(ac_posMS2,"data/ac_posMS2.csv",row.names = F)

ac_pls<-InitDataObjects("conc", "stat", TRUE)
ac_pls<-Read.TextData(ac_pls, "data/ac_posMS2.csv", "rowp", "disc");
ac_pls<-SanityCheckData(ac_pls)
ac_pls<-ReplaceMin(ac_pls);
ac_pls<-PreparePrenormData(ac_pls)
ac_pls<-Normalization(ac_pls, "NULL", "NULL", "NULL", ratio=FALSE, ratioNum=20)

ac_pls<-PLSR.Anal(ac_pls, reg=TRUE)

ac_pls<-PlotPLSPairSummary(ac_pls, "figure/MetaboAnalystR_PLSDA/ac pls summary_pos", "png", 72, width=NA, 5)

ac_pls<-PlotPLS2DScore(ac_pls, "figure/MetaboAnalystR_PLSDA/ac pls 2D score plot_pos", "png", 72, width=NA, 1,2,0.95,0,0)

ac_pls<-PlotPLSLoading(ac_pls, "figure/MetaboAnalystR_PLSDA/ac pls loading_pos", "png", 72, width=NA, 1, 2);

ac_pls<-PLSDA.CV(ac_pls, "T",5, "Q2")
ac_pls<-PlotPLS.Classification(ac_pls, "figure/MetaboAnalystR_PLSDA/ac pls cross validation_pos", "png", 72, width=NA)

ac_pls_vip<-PlotPLS.Imp(ac_pls, "figure/MetaboAnalystR_PLSDA/ac pls_vip_pos", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)

ac_vip <- ac_pls_vip$analSet$plsda$vip.mat

ac_vip_d <- as.data.frame(ac_vip)
ac_vip_d <- dplyr::select(ac_vip_d,ac_vip_c1='Comp. 1')

write.csv(ac_vip_d,"data/ac plsda vip_pos.csv")
```

```{r PLS analysis of AB using MetaboAnalystR,include=FALSE}
library(MetaboAnalystR)

ab_posMS2$Label=c(1:16,-1:-16)
ab_posMS2 <- ab_posMS2 %>% dplyr::select(sample,Label,everything()) %>% dplyr::select(-class)

write.csv(ab_posMS2,"data/ab_posMS2.csv",row.names = F)

ab_pls<-InitDataObjects("conc", "stat", TRUE)
ab_pls<-Read.TextData(ab_pls, "data/ab_posMS2.csv", "rowp", "disc");
ab_pls<-SanityCheckData(ab_pls)
ab_pls<-ReplaceMin(ab_pls);
ab_pls<-PreparePrenormData(ab_pls)
ab_pls<-Normalization(ab_pls, "NULL", "NULL", "NULL", ratio=FALSE, ratioNum=20)

ab_pls<-PLSR.Anal(ab_pls, reg=TRUE)

ab_pls<-PlotPLSPairSummary(ab_pls, "figure/MetaboAnalystR_PLSDA/ab pls summary_pos", "png", 72, width=NA, 5)

ab_pls<-PlotPLS2DScore(ab_pls, "figure/MetaboAnalystR_PLSDA/ab pls 2D score plot_pos", "png", 72, width=NA, 1,2,0.95,0,0)

ab_pls<-PlotPLSLoading(ab_pls, "figure/MetaboAnalystR_PLSDA/ab pls loading_pos", "png", 72, width=NA, 1, 2);

ab_pls<-PLSDA.CV(ab_pls, "T",5, "Q2")
ab_pls<-PlotPLS.Classification(ab_pls, "figure/MetaboAnalystR_PLSDA/ab pls cross validation_pos", "png", 72, width=NA)

ab_pls_vip<-PlotPLS.Imp(ab_pls, "figure/MetaboAnalystR_PLSDA/ab pls_vip_pos", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)

ab_vip <- ab_pls_vip$analSet$plsda$vip.mat

ab_vip_d <- as.data.frame(ab_vip)
ab_vip_d <- dplyr::select(ab_vip_d,ab_vip_c1='Comp. 1')

write.csv(ab_vip_d,"data/ab plsda vip_pos.csv")
```

```{r PLS analysis of AD using MetadoAnalystR,include=FALSE}
library(MetaboAnalystR)

ad_posMS2$Label=c(1:16,-1:-16)
ad_posMS2 <- ad_posMS2 %>% dplyr::select(sample,Label,everything()) %>% dplyr::select(-class)

write.csv(ad_posMS2,"data/ad_posMS2.csv",row.names = F)

ad_pls<-InitDataObjects("conc", "stat", TRUE)
ad_pls<-Read.TextData(ad_pls, "data/ad_posMS2.csv", "rowp", "disc");
ad_pls<-SanityCheckData(ad_pls)
ad_pls<-ReplaceMin(ad_pls);
ad_pls<-PreparePrenormData(ad_pls)
ad_pls<-Normalization(ad_pls, "NULL", "NULL", "NULL", ratio=FALSE, ratioNum=20)

ad_pls<-PLSR.Anal(ad_pls, reg=TRUE)

ad_pls<-PlotPLSPairSummary(ad_pls, "figure/MetaboAnalystR_PLSDA/ad pls summary_pos", "png", 72, width=NA, 5)

ad_pls<-PlotPLS2DScore(ad_pls, "figure/MetaboAnalystR_PLSDA/ad pls 2D score plot_pos", "png", 72, width=NA, 1,2,0.95,0,0)

ad_pls<-PlotPLSLoading(ad_pls, "figure/MetaboAnalystR_PLSDA/ad pls loading_pos", "png", 72, width=NA, 1, 2);

ad_pls<-PLSDA.CV(ad_pls, "T",5, "Q2")
ad_pls<-PlotPLS.Classification(ad_pls, "figure/MetaboAnalystR_PLSDA/ad pls cross validation_pos", "png", 72, width=NA)

ad_pls_vip<-PlotPLS.Imp(ad_pls, "figure/MetaboAnalystR_PLSDA/ad pls_vip_pos", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)

ad_vip <- ad_pls_vip$analSet$plsda$vip.mat

ad_vip_d <- as.data.frame(ad_vip)
ad_vip_d <- dplyr::select(ad_vip_d,ad_vip_c1='Comp. 1')

write.csv(ad_vip_d,"data/ad plsda vip_pos.csv")
```

```{r PLS analysis of BC using MetbcoAnalystR,include=FALSE}
library(MetaboAnalystR)

bc_posMS2$Label=c(1:16,-1:-16)
bc_posMS2 <- bc_posMS2 %>% dplyr::select(sample,Label,everything()) %>% dplyr::select(-class)

write.csv(bc_posMS2,"data/bc_posMS2.csv",row.names = F)

bc_pls<-InitDataObjects("conc", "stat", TRUE)
bc_pls<-Read.TextData(bc_pls, "data/bc_posMS2.csv", "rowp", "disc");
bc_pls<-SanityCheckData(bc_pls)
bc_pls<-ReplaceMin(bc_pls);
bc_pls<-PreparePrenormData(bc_pls)
bc_pls<-Normalization(bc_pls, "NULL", "NULL", "NULL", ratio=FALSE, ratioNum=20)

bc_pls<-PLSR.Anal(bc_pls, reg=TRUE)

bc_pls<-PlotPLSPairSummary(bc_pls, "figure/MetaboAnalystR_PLSDA/bc pls summary_pos", "png", 72, width=NA, 5)

bc_pls<-PlotPLS2DScore(bc_pls, "figure/MetaboAnalystR_PLSDA/bc pls 2D score plot_pos", "png", 72, width=NA, 1,2,0.95,0,0)

bc_pls<-PlotPLSLoading(bc_pls, "figure/MetaboAnalystR_PLSDA/bc pls loading_pos", "png", 72, width=NA, 1, 2);

bc_pls<-PLSDA.CV(bc_pls, "T",5, "Q2")
bc_pls<-PlotPLS.Classification(bc_pls, "figure/MetaboAnalystR_PLSDA/bc pls cross validation_pos", "png", 72, width=NA)

bc_pls_vip<-PlotPLS.Imp(bc_pls, "figure/MetaboAnalystR_PLSDA/bc pls_vip_pos", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)

bc_vip <- bc_pls_vip$analSet$plsda$vip.mat

bc_vip_d <- as.data.frame(bc_vip)
bc_vip_d <- dplyr::select(bc_vip_d,bc_vip_c1='Comp. 1')

write.csv(bc_vip_d,"data/bc plsda vip_pos.csv")
```



```{r PLSDA and time series based variable selection, include=F}
library(tidyverse)
timese_result <- timese_result %>% dplyr::select(-type) %>% add_rownames("mid")
ac_vip_d <- add_rownames(ac_vip_d,"mid")
ab_vip_d <- add_rownames(ab_vip_d,"mid")
bc_vip_d <- add_rownames(bc_vip_d,"mid")
pls_times_result_pos <- left_join(timese_result,ac_vip_d,by="mid")
pls_times_result_pos <- left_join(pls_times_result_pos,ab_vip_d,by="mid")
pls_times_result_pos <- left_join(pls_times_result_pos,bc_vip_d,by="mid")
write.csv(pls_times_result_pos,"data/PLSDA and time series results_pos.csv")
pls.time.vip <- dplyr::filter(pls_times_result_pos,ac_vip_c1>2|ab_vip_c1>2|bc_vip_c1>2)
pls.time.vipAC <- dplyr::filter(pls_times_result_pos,ac_vip_c1>2)
pls.time.vip2 <- dplyr::filter(pls.time.vip,Hotelling.T2>99)
write.csv(pls.time.vip,"data/metabolites VIP over 2.csv",row.names = F)
write.csv(pls.time.vipAC,"data/pls.time.vipAC.csv",row.names = F)
```



```{r data files for plotting, include=F}

mstus_pos <- read.csv("data/mstus_pos.csv",stringsAsFactors = F,header = F)
colnames(mstus_pos) <- mstus_pos[1,]
mstus_pos <- as.data.frame(mstus_pos[-1,])
mstus_col <- names(mstus_pos) %>% str_replace("X","")
names(mstus_pos) <- mstus_col
mstus_pos <- dplyr::select(mstus_pos,-class)

colnames(mstus_pos) <- pos_ms2$MS2.name[match(names(mstus_pos),pos_ms2$id)]


colmstus <- names(mstus_pos)
colmstus[is.na(colmstus)] <- "sample"
names(mstus_pos) <- colmstus
mstus_pos <- mstus_pos %>% dplyr::arrange(sample)%>% dplyr::slice(-43,-44,-61,-62)
mstus_pos$class <- rep(c("A diet","B diet","C diet","D diet"),times=c(16,16,16,16))
mstus_pos <- dplyr::select(mstus_pos,sample,class,everything())

mstusABC_pos <- dplyr::slice(mstus_pos,1:48)

pls.time.vipAC2 <- dplyr::slice(pls.time.vipAC,-38,-13,-21,-7)
mid <- pls.time.vip$mid
midAC2 <- pls.time.vipAC2$mid
sampid <- mstusABC_pos$sample
classid <- mstusABC_pos$class

vip.file.pos <- mstusABC_pos[,colnames(mstusABC_pos) %in% mid]
vip.file.pos$sample <- sampid
vip.file.pos$class <- classid

rt_mz_pos <- pos_inf[pos_inf$MS2.name %in% midAC,]
rt_mz_pos <- dplyr::rename(rt_mz_pos,mid=MS2.name)
met_inf <- left_join(rt_mz_pos,pls.time.vipAC,by="mid")
write.csv(met_inf,"data/information of metabolites selected_pos.csv",row.names = F)

rt_mz_pos2 <- pos_inf[pos_inf$MS2.name %in% midAC2,]
rt_mz_pos2 <- dplyr::rename(rt_mz_pos2,mid=MS2.name)
met_inf2 <- left_join(rt_mz_pos2,pls.time.vipAC2,by="mid")
write.csv(met_inf2,"data/information of metabolites selected_pos2.csv",row.names = F)


vip.file.posAC <- mstusABC_pos[,colnames(mstusABC_pos) %in% midAC]
vip.file.posAC$sample <- sampid
vip.file.posAC$class <- classid

vip.file.posAC2 <- mstusABC_pos[,colnames(mstusABC_pos) %in% midAC2]
vip.file.posAC2$sample <- sampid
vip.file.posAC2$class <- classid

write.csv(vip.file.posAC,"data/vip.file.posAC.csv",row.names = F)

vip.file.pos1 <- dplyr::select(vip.file.pos,sample,class,1:9)
vip.file.pos2 <- dplyr::select(vip.file.pos,sample,class,10:18)
vip.file.pos3 <- dplyr::select(vip.file.pos,sample,class,19:27)
vip.file.pos4 <- dplyr::select(vip.file.pos,sample,class,28:36)
vip.file.pos5 <- dplyr::select(vip.file.pos,sample,class,37:45)
vip.file.pos6 <- dplyr::select(vip.file.pos,sample,class,46:54)


vip.p.pos1 <- gather(vip.file.pos1,key="mid",value = "Abundance",-sample,-class)
vip.p.pos2 <- gather(vip.file.pos2,key="mid",value = "Abundance",-sample,-class)
vip.p.pos3 <- gather(vip.file.pos3,key="mid",value = "Abundance",-sample,-class)
vip.p.pos4 <- gather(vip.file.pos4,key="mid",value = "Abundance",-sample,-class)
vip.p.pos5 <- gather(vip.file.pos5,key="mid",value = "Abundance",-sample,-class)
vip.p.pos6 <- gather(vip.file.pos6,key="mid",value = "Abundance",-sample,-class)

vip.p.posAC <- gather(vip.file.posAC, key = "mid", value = "Abundance",-sample, -class)
vip.p.posAC2 <- gather(vip.file.posAC2, key = "mid", value = "Abundance",-sample, -class)
```

```{r plot 1,warning=FALSE,echo=FALSE}
library(tidyverse)
p1 <- ggplot(data=vip.p.pos1,mapping = aes(x=class,y=Abundance))+geom_boxplot()+facet_wrap(~mid,nrow = 3)
p1+ylim(0,0.002)+xlab("Dietary pattern")+ggtitle("尿液代谢产物在不同膳食模式下的峰面积变化图1")+theme(plot.title=element_text(size=rel(1.5), lineheight=.9, hjust=0.5,family="Times"))


p2 <- ggplot(data=vip.p.posAC,mapping = aes(x=class,y=Abundance))+geom_boxplot()+facet_wrap(~mid,nrow = 6)
p2+ylim(0,0.003)+xlab("Dietary pattern")+theme(plot.title=element_text(size=rel(1.5), lineheight=.9, hjust=0.5,family="Times"))

p3 <- ggplot(data=vip.p.posAC2,mapping = aes(x=class,y=Abundance))+geom_boxplot()+facet_wrap(~mid,nrow = 8)+theme(strip.text.x = element_text(size =15,family="Times"))
p3+ylim(0,0.003)+xlab("Dietary pattern")+theme(text=element_text(size=20, lineheight=.9, hjust=0.5,family="Times"))
```


```{r plot 2,warning=FALSE,echo=FALSE}
library(tidyverse)
p2 <- ggplot(data=vip.p.pos2,mapping = aes(x=class,y=Abundance))+geom_boxplot()+facet_wrap(~mid,nrow = 3)
p2+ylim(0,0.002)+xlab("Dietary pattern")+ggtitle("尿液代谢产物在不同膳食模式下的峰面积变化图2")+theme(plot.title=element_text(size=rel(1.5), lineheight=.9, hjust=0.5,family="Times"))

```

```{r plot 3,warning=FALSE,echo=FALSE}
library(tidyverse)
p3 <- ggplot(data=vip.p.pos3,mapping = aes(x=class,y=Abundance))+geom_boxplot()+facet_wrap(~mid,nrow = 3)
p3+ylim(0,0.002)+xlab("Dietary pattern")+ggtitle("尿液代谢产物在不同膳食模式下的峰面积变化图3")+theme(plot.title=element_text(size=rel(1.5), lineheight=.9, hjust=0.5,family="Times"))

```


```{r plot 4,warning=FALSE,echo=FALSE}
library(tidyverse)
p4 <- ggplot(data=vip.p.pos4,mapping = aes(x=class,y=Abundance))+geom_boxplot()+facet_wrap(~mid,nrow = 3)
p4+ylim(0,0.002)+xlab("Dietary pattern")+ggtitle("尿液代谢产物在不同膳食模式下的峰面积变化图4")+theme(plot.title=element_text(size=rel(1.5), lineheight=.9, hjust=0.5,family="Times"))

```

```{r plot 5,warning=FALSE,echo=FALSE}
library(tidyverse)
p5 <- ggplot(data=vip.p.pos3,mapping = aes(x=class,y=Abundance))+geom_boxplot()+facet_wrap(~mid,nrow = 3)
p5+ylim(0,0.002)+xlab("Dietary pattern")+ggtitle("尿液代谢产物在不同膳食模式下的峰面积变化图5")+theme(plot.title=element_text(size=rel(1.5), lineheight=.9, hjust=0.5,family="Times"))

```

```{r plot 6,warning=FALSE,echo=FALSE}
library(tidyverse)
p6 <- ggplot(data=vip.p.pos6,mapping = aes(x=class,y=Abundance))+geom_boxplot()+facet_wrap(~mid,nrow = 3)
p6+ylim(0,0.002)+xlab("Dietary pattern")+ggtitle("尿液代谢产物在不同膳食模式下的峰面积变化图6")+theme(plot.title=element_text(size=rel(1.5), lineheight=.9, hjust=0.5,family="Times"))

```


```{r  AC mixOmics analysis, include=FALSE}
#multilevel design: a vector to indicate each individual
ml2 <- data.frame(rep(c(1:16),times=2))
ml2 <- dplyr::rename(ml2,sample=1)

ml3 <- data.frame(rep(c(1:16),times=3))
ml3 <- dplyr::rename(ml3,sample=1)

# group identifier
group_ac <- rep(c("a","c"),times=c(16,16))
group3 <- rep(c("a","b","c"),times=c(16,16,16))

library(mixOmics)

# sample file:data frame to matrix
ac_posMS2_m <- ac_posMS2[,-1:-2]
rownames(ac_posMS2_m) <- ac_posMS2[,1]
ac_posMS2_m <- data.matrix(ac_posMS2_m)

## pls-da AC
plsda.ac<- plsda(ac_posMS2_m, Y = group_ac, multilevel = ml2, ncomp = 10)

plotIndiv(plsda.ac, ind.names = ml2,
          group = group_ac, 
          legend = TRUE,
          title = 'AC multilevel PLS-DA, comp 1 - 2')

set.seed(2567) # for reproducibility, only when the `cpus' argument is not used
perf.plsda.ac <- perf(plsda.ac, validation = "loo", folds = 5, 
                         progressBar = FALSE, auc = TRUE, nrepeat = 10) 

plot(perf.plsda.ac, col = color.mixo(5:7), sd = TRUE, legend.position = "horizontal")

auc.plsda.ac = auroc(plsda.ac, roc.comp = 2)

##Tuning spls-da AD
list.keepX <- c(1:10,  seq(20, 300, 10))

tune.splsda.ac <- tune.splsda(ac_posMS2_m, Y = group_ac, multilevel = ml2, ncomp = 2, validation = 'Mfold', folds = 5, 
                                 progressBar = TRUE, dist = 'max.dist', measure = "BER",
                                 test.keepX = list.keepX, nrepeat = 10, cpus = 2)

error_ac <- tune.splsda.ac$error.rate 

ncomp_ac <- tune.splsda.ac$choice.ncomp$ncomp


select.keepX_ac <- tune.splsda.ac$choice.keepX[1:2]  # optimal number of variables to select

splsda.ac <- splsda(ac_posMS2_m, Y = group_ac, multilevel = ml2,ncomp = 2, keepX = select.keepX_ac) 

plotIndiv(splsda.ac, 
          group = group_ac, ind.names = FALSE, 
          ellipse = TRUE, legend = TRUE,
          title = 'sPLS-DA on AC, comp 1 & 2')

auc.splsda.ac = auroc(splsda.ac, roc.comp = 2)

set.seed(40) # for reproducibility, only when the `cpus' argument is not used
# takes about 1 min to run
perf.ac<- perf(splsda.ac, validation = "Mfold", folds = 5,
                   dist = 'max.dist', nrepeat = 10,
                   progressBar = FALSE) 

# here we match the selected variables to the stable features
ind.match = match(selectVar(splsda.ac, comp = 1)$name, 
                  names(perf.ac$features$stable[[1]]))
#extract the frequency of selection of those selected variables
Freq = as.numeric(perf.ac$features$stable[[1]][ind.match])

data.frame(selectVar(splsda.ac, comp = 1)$value, Freq)

```

