---
title: "R Notebook"
output: html_notebook
---

```{r packagelowding}
library(tidyverse)
library(MetaboAnalystR)
```


```{r transpose}
#import mean concentraiton data in postive mode
posmean_sub <- read_csv("posmean_sub.csv")
#import compound id data file
pos_comid <- read_csv("pos_comid.csv")
#select subjects only, exclude QC and Mean values
posmean_eq <- dplyr::select(posmean_sub,id,matches("^[ABCD]"))
#Transpose data frame:subjects in row
posmean <- posmean_eq %>%
  rename(metid=id) %>%
  gather(subid,value,-metid) %>%
  spread(metid,value)
#Change format of subject id and add treatment class for each row
subid2 <- posmean$subid %>% str_replace("[0-9][0-9]_pos\\.[ABCD]","_")
treat <- rep(c("Adiet","Bdiet","Cdiet","Ddiet"),times=c(16,16,18,18))
posmean_group <- posmean %>% dplyr::select(-subid) %>% add_column(subid=subid2,treatment=treat) %>% dplyr::select(subid,treatment,everything())

#Subject number 11 and 12 didnot finish diet A and B, remove these two samples from data
posmean_group2 <- posmean_group %>% slice(-43,-44,-61,-62)
#get subject id and treatment for the sample
subid_int <- posmean_group2$subid %>% str_replace("^[ABCD]_","s") #To get a number for each subject
treatment2 <- posmean_group2$treatment 

#generate two group file
glabel <- c(1:16,-1:-16
          )
#files for group A and B
posmean_ab <- posmean_group2 %>% slice(1:32) %>% dplyr::select(-treatment) %>% add_column(label=glabel) %>% dplyr::select(subid,label,everything())

#files for group A and C
posmean_ac <- posmean_group2 %>% slice(1:16,33:48) %>% dplyr::select(-treatment) %>% add_column(label=glabel) %>% dplyr::select(subid,label,everything())

#files for group A and D
posmean_ad <- posmean_group2 %>% slice(1:16,49:64) %>% dplyr::select(-treatment) %>% add_column(label=glabel) %>% dplyr::select(subid,label,everything())

#files for group B and C
posmean_bc <- posmean_group2 %>% slice(17:32,33:48) %>% dplyr::select(-treatment) %>% add_column(label=glabel) %>% dplyr::select(subid,label,everything())

#files for group B and D
posmean_bd <- posmean_group2 %>% slice(17:32,49:64) %>% dplyr::select(-treatment) %>% add_column(label=glabel) %>% dplyr::select(subid,label,everything())

#files for group C and D
posmean_cd <- posmean_group2 %>% slice(33:64) %>% dplyr::select(-treatment) %>% add_column(label=glabel) %>% dplyr::select(subid,label,everything())

#get files for time-series analysis
Subject <- rep(c(1:16),times=4)
timet  <- rep(c(1,2,3,4),times=c(16,16,16,16))
posmean_metr <- posmean_group2  %>% add_column(Subject=Subject,Time=timet) %>% dplyr::select(subid,Subject,Time,everything(),-treatment) %>% arrange(Subject,Time)

```
```{r normalization}
#write posmean_metr to csv
write_csv(posmean_metr,"posmean_metr.csv")

#Model definition and missing value checks:time-series analysis with concentration and samples in row
mSet<-InitDataObjects("conc", "ts", FALSE)
mSet<-SetDesignType(mSet, "time0")
mSet<-Read.TextData(mSet, "posmean_metr.csv", "rowts", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-FilterVariable(mSet, "iqr", "F", 25)
mSet<-PreparePrenormData(mSet)

#Normalization
mSet<-Normalization(mSet, "NULL", "LogNorm", "AutoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
```
